[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
TwistedBoundaryConditions = "2af597a4-5342-44f0-9c3f-26623f0804b1"

[compat]
Documenter = "1"
Literate = "2"
TwistedBoundaryConditions = "0.1"
